/*
    Copyright (C) 2015,2016,2017  Diversity Arrays Technology, Pty Ltd.
    
    Barcode Printer may be redistributed and may be modified under the terms
    of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option)
    any later version.
    
    Barcode Printer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License
    along with Barcode Printer.  If not, see <http://www.gnu.org/licenses/>.
*/
package com.diversityarrays.dartapps.barcode;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * 
 * @author Alex Spence
 *
 */
public class BarcodePrinterAbout {
	
	private final static String ABOUT = "<html>Copyright (c) 2017 Diversity Arrays Technology (DArT).<br><br>"
			+ "Developers: <ul>"
			+ "<li> Alexander Spence </li>"
			+ "<li> Brian Pearce </li>"
			+ "</ul>"
			+ "This Software uses the following Licenses/Libraries: <br>"
			+ "<ul><li>GNU Affero General Public License Version 3.0:</li></ul>"
			+ "itextpdf-5.4.0"
			+ "<ul><li>Apache License Version 2.0:</li></ul>"
			+ "zxing-core, zxing-javase, collections-generic-4.0.1<br><br>"
			+ ""
			+ "<b>NOTE:</b<br>"
			+ "Individual Licenses can be found in the directory of the same name<br>"
			+ "provided with this distribution.<br><br>"
			+ ""
			+ "iText PDF Java library was used for the generation of all .PDF output files<br> "
			+ "generated by this application.</html>";
	
	public static void showAbout(JFrame frame) {
		JLabel area = new JLabel(ABOUT);
		
		JDialog dialog = new JDialog(frame, "About");
		
		dialog.add(area);
		dialog.pack();
		dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		dialog.setLocationRelativeTo(frame.getContentPane());
		
		dialog.setVisible(true);
	}
}
